services:
  emboxd:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - emboxd:latest
    # Alternatively, once you have a Docker image published:
    # image: yourusername/emboxd:latest
    container_name: emboxd
    network_mode: bridge
    ports:
      - "9001:9001"  # Map host port 9001 to container port 9001
    volumes:
      - ./config:/config  # Mount local config directory
      - ./logs:/logs      # Mount local logs directory
      - ./data:/data      # Mount local data directory
      - playwright-cache:/root/.cache/ms-playwright  # Persist Playwright browser installations
    environment:
      - TZ=America/Denver            # Set your timezone here, e.g., America/New_York
      - HISTORY_SIZE=100  # Number of events to keep in history
      - LOG_JSON=false    # Set to true for JSON formatted logs
      - LOG_DIR=/logs     # Explicitly set log directory to absolute path
      - PLAYWRIGHT_BROWSERS_PATH=/root/.cache/ms-playwright
      - PORT=9001        # Port for the application to listen on
      # - LOG_LEVEL=info  # Log level (info, debug, warn, error)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--method=GET", "-O", "/dev/null", "http://localhost:9001/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    # Resource constraints - uncomment and adjust as needed
    # These help prevent the container from using too many resources
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
    labels:
      - "com.github.emboxd.description=Letterboxd integration for Plex and Emby"
      - "com.github.emboxd.version=latest"
      - "com.github.emboxd.url=https://github.com/computer-geek64/emboxd"
      - "org.opencontainers.image.authors=EmBoxd Maintainers"
      - "org.opencontainers.image.source=https://github.com/computer-geek64/emboxd"
      - "org.label-schema.name=EmBoxd"
      - "org.label-schema.description=Live sync server for Letterboxd users with self-hosted media platforms"

volumes:
  playwright-cache:
    # Using a named volume to persist the Playwright browser installations
    # This prevents having to re-download browsers after container recreation